local_costmap:
  global_frame: /odom

  plugins:
    - {name: obstacles,       type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  #We'll configure this costmap to be a rolling window... meaning it is always
  #centered at the robot
  static_map: false
  rolling_window: true

  update_frequency: 10

  width: 5.0
  height: 5.0
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0
