global_costmap:
  static_map: true
  rolling_window: false

  global_frame: /odom

  update_frequency: 3.0
  publish_voxel_map: true

  width: 30.0
  height: 30.0
  resolution: 0.2
  origin_x: -15.0
  origin_y: -15.0

  plugins:
    - {name: obstacles,       type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
