base_local_planner: teb_local_planner/TebLocalPlannerROS

TebLocalPlannerROS:

 odom_topic: /odom
 map_frame: /odom

 # footprint_model that is used by local planner. This is different from costmap
 # footprint!
 footprint_model:
   type: "two_circles"
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
